services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    healthcheck:
      # https://dev.mysql.com/doc/refman/8.0/en/testing-server.html
      test:
        [
          "CMD",
          "mysqladmin",
          "version",
          "-u",
          "${DB_USER}",
          "-p${DB_USER_PASSWORD}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --maxmemory-policy noeviction
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  adminer:
    image: adminer
    container_name: db-gui
    restart: always
    ports:
      - 8080:8080

  server:
    container_name: node-app
    build:
      context: .
      target: ${ENVIRONMENT}
    volumes:
      - .:/usr/backend
    ports:
      - ${PORT}:${PORT}
    depends_on:
      mysql:
        condition: service_healthy
