# Use root/example as user/password credentials
# https://hub.docker.com/_/mongo
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - ./src/db/volume:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${PANEL_PORT}:${PANEL_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/
